In [36]:
# Importing required libraries to run super mario bros on gym
from nes_py.wrappers import JoypadSpace
import gym_super_mario_bros
from gym.wrappers import GrayScaleObservation
from pathlib import Path
from gym_super_mario_bros.actions import SIMPLE_MOVEMENT

In [47]:
env = gym_super_mario_bros.make("SuperMarioBros-v0")
env = JoypadSpace(env, SIMPLE_MOVEMENT)
env = GrayScaleObservation(env, keep_dim=True)
print(env.action_space.n)

path = Path('checkpoints')
print(type(path))

7
<class 'pathlib.WindowsPath'>


In [48]:
import torch
torch.cuda.is_available()

True

In [49]:
# Testing tensor types
done = True
tensor_done = torch.tensor([done])
print(tensor_done)
t_done = torch.BoolTensor([done])
t_done

tensor([True])


tensor([True])

In [50]:
# setting up gym environment and running a short game
done = True
for step in range(5000):
    if done:
        state = env.reset()
    state_tensor = torch.FloatTensor(state).cuda().unsqueeze(0)
    state, reward, done, info = env.step(env.action_space.sample())
    env.render()
env.close() 


(array([[[140],
        [140],
        [140],
        ...,
        [140],
        [140],
        [140]],

       [[140],
        [140],
        [140],
        ...,
        [140],
        [140],
        [140]],

       [[140],
        [140],
        [140],
        ...,
        [140],
        [140],
        [140]],

       ...,

       [[214],
        [124],
        [124],
        ...,
        [124],
        [124],
        [  0]],

       [[214],
        [124],
        [124],
        ...,
        [124],
        [  0],
        [  0]],

       [[124],
        [  0],
        [  0],
        ...,
        [  0],
        [  0],
        [124]]], dtype=uint8), 0.0, False, {'coins': 0, 'flag_get': False, 'life': 2, 'score': 0, 'stage': 1, 'status': 'small', 'time': 400, 'world': 1, 'x_pos': 40, 'x_pos_screen': 40, 'y_pos': 79})
